project:
  type: website
  output-dir: docs

website:
  title: "606"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Aula1.qmd
        text: Aula1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

